### ISSUE TITLE
[Dialog] body pointer-events: none remains after closing

### ISSUE THREAD

**Issue by 413n** [radix-ui/primitives#1241]
### Current Behavior

With `Dialog` version 0.1.7 the pointer-events seems to remain on the `body` with the Chrome device emulator using a mobile device  (e.g. iPad Air), while in the 0.1.6 it works fine.

### Expected behavior

The pointer-events should always be removed from the body after the closing animation has finished.

### Reproducible example

The 2 repos are identical, except the `@radix-ui/react-dialog` version:
- [Version 0.1.7](https://codesandbox.io/s/dialog-0-1-7-pointer-events-bug-jhp0nd)
- [Version 0.1.6](https://codesandbox.io/s/dialog-0-1-6-pointer-events-bug-zgt5um)

### Additional context

I forked the `radix-ui/design-system` repo on codesandbox to reproduce this bug keeping the original code but changing just the version of the `@radix-ui/react-dialog`.

**Note**: In the version 0.1.7, the problem should be solved by removing the `close` animation from the Content

**Comment by benoitgrelard** [comment]
Hi @413n,

I can reproduce the bug using your sandboxes.
Thanks for reporting.

**Comment by janhoogeveen** [comment]
@benoitgrelard Seems like this is the same as https://github.com/radix-ui/primitives/issues/1236. Since this one has a working example already, should we close the other one? 👍🏻

**Comment by benoitgrelard** [comment]
I've been wondering too, but I haven't verified fully that it is indeed the same.
Once confirmed I will close one as duplicate.

**Comment by HeatedGrace** [comment]
I use the AlertDialog and have the same question. 
When AlertDialog.Trigger controls the open, body element can remove the 'pointer-events' normally.
But when i use the AlertDialog.Root open attribute, body element still keep the 'pointer-events' after close.

**Comment by benoitgrelard** [comment]
I am still able to replicate this in `main`.
Some more observation:
- It only appears to be an issue when there's a close CSS animation on the `Content` part, ie. when it hands around

**Comment by PeerRich** [comment]
@benoitgrelard has this been fixed? we're experiencing this at https://github.com/calcom/cal.com/issues/2328

**Comment by benoitgrelard** [comment]
Hey @PeerRich yes it has been fixed and released as part of the v1 release. Have you upgraded?

**Comment by PeerRich** [comment]
doesn't seem like we did? https://github.com/calcom/cal.com/blob/b42f0ffadd525c8ed6d79e1034e8122dbe0e8036/apps/web/package.json#L52-L61

**Comment by benoitgrelard** [comment]
Yeah that would be why then 👍

**Comment by PeerRich** [comment]
how hard is the upgrade? is there an upgrade document?

**Comment by davidthomasparks** [comment]
I'm still experiencing this issue on the latest version. I'm opening a dialog from a dropdown and once dismissing the dialog pointer events none is still set on the body

**Comment by benoitgrelard** [comment]
@davidthomasparks, AFAIK that should be fixed. Are you able to reproduce the issue in a codesandbox?

**Comment by angelod1as** [comment]
@benoitgrelard also still happening in my project but sadly I couldn't reproduce it in isolation :(

**Comment by benoitgrelard** [comment]
@davidthomasparks @angelod1as, are you sure all the involved components are using their respective latest `1.0.0` versions?

**Comment by milo-** [comment]
@benoitgrelard I'm also experiencing this with 1.0.0

**Comment by benoitgrelard** [comment]
@milo, same questions then, are you able to reproduce this in a sandbox?

**Comment by dcheglakov** [comment]
I also experienced this issue, but on `1.0.0` it looks like this issue has been fixed. I've created a [sandbox for the test](https://codesandbox.io/s/nifty-diffie-wfs3wu?file=/src/App.js). And guys make sure that dropdown and dialog on the same version. I had dialog on version `1.0.0` and dropdown on `0.1.6`. Maybe this will help.

**Comment by davidthomasparks** [comment]
> @davidthomasparks @angelod1as, are you sure all the involved components are using their respective latest `1.0.0` versions?

Here is a screenshot of the issue. A dropdown item controls the open state of a modal (both dropdown and modal are 1.0). The modal is controlled. Once I close the modal, the pointer-events: none stays on the body. 

It is not an issue opening a modal outside of a dropdown. 
<img width="801" alt="Screen Shot 2022-08-26 at 2 16 09 PM" src="https://user-images.githubusercontent.com/97011546/186991909-bcc82378-18fd-4efb-9c96-4656cde4cc21.png">

**Comment by davidthomasparks** [comment]
I think it may be a timing thing. I added a timeout to setting the modal opened and the issue isn't there anymore. Probably some race condition for toggling pointer events on the body when the dialog closes and the modal opens?

**Comment by dcheglakov** [comment]
> I think it may be a timing thing or a browser queue thing. I added a 1ms setTimeout to setting the modal opened and the issue isn't there anymore. Probably some race condition for toggling pointer events on the body when the dialog closes and the modal opens? Like a nextTick VueJs workaround or something @benoitgrelard

@davidthomasparks try to close dropdown and then open modal.

**Comment by benoitgrelard** [comment]
@davidthomasparks, if you could create a reduced codesandbox with your issue, we can take a look, it is hard to go by just looking at code screenshots unfortunately.

**Comment by MaximeHeckel** [comment]
Hey @benoitgrelard  👋  I have a repro for this: https://codesandbox.io/s/sad-varahamihira-qc83r8?file=/src/App.js

It's happening to my team right now as we're transitioning to react 18.2.0 (worked well on React 17.0.2). We're still using the version 1.0.0 for both:
- `@radix-ui/dialog`
- `@radix-ui/react-dropdown-menu`

will try to see if it happens on the latest version.

The codesandbox above has some abstraction that we have in our design system that I transcribed here to repro the issue. Maybe it's caused by this? 🤔

**Comment by benoitgrelard** [comment]
Hey @MaximeHeckel,

I'm not sure what I'm supposed to see here but from what I can see in the sandbox, when I click the button I see "hello" in the console and pointer events aren't disabled so it seems to work fine.

Am I missing something?

PS: Side note, when composing these 2 together you'll need to manage focus as right now, focus is lost when you close the dialog.

**Comment by MaximeHeckel** [comment]
Oh sorry I accidentally pinned the dependencies and ended up with both `1.0.0` instead of `^1.0.0`. Looks like it happened when you had
- `@radix-ui/dialog: 1.0.2`
- `@radix-ui/react-dropdown-menu: 1.0.0`

**Comment by benoitgrelard** [comment]
> Again not a big issue since this all seems to be addressed when using the latest version of both packages

Yeah it's probably due to version mismatch. Unfortunately with independent versioning one thing that is tricky to do is to coordinate changes across dependencies. In this case both of these packages use a common package to deal with the layering, and if you use a version of each package which depends on a different version of that common dep, it will break.

So yeah the general advice we give so far for those is to ensure you are always using the latest version of each primitive.

**Comment by klanthier** [comment]
> > I think it may be a timing thing or a browser queue thing. I added a 1ms setTimeout to setting the modal opened and the issue isn't there anymore. Probably some race condition for toggling pointer events on the body when the dialog closes and the modal opens? Like a nextTick VueJs workaround or something @benoitgrelard
> 
> @davidthomasparks try to close dropdown and then open modal.

FYI I had the same issue -> I was opening the modal from a radix dropdown event. Adding a 1ms delay prevent this issue from happening. Thanks!

**Comment by rosszurowski** [comment]
Chiming in to say that our team ran into this issue too. We had upgraded `@radix-ui/react-dropdown-menu` to the latest version at the prompting of a dependabot PR, but noticed the `pointer-events: none` style rule stuck around after closing a dialog opened by the dropdown menu.

Upgrading all our components to the latest version fixed this issue. I suspect this is because differing versions of some underlying library (eg. `@radix-ui/react-dismissable-layer`) didn't play well with each other. If that _is_ the case, it'd be nice to have some version check in development when multiple versions of a sub-dependency are present. I'm happy to file a separate issue for that if needed.

**Comment by andy-hook** [comment]
@rosszurowski You're absolutely right and it's [on our list](https://github.com/radix-ui/primitives/issues/1088) to improve

**Comment by rosszurowski** [comment]
Ah, great. Sorry — I should've looked for that before suggesting. Thanks!

**Comment by joaom00** [comment]
@maxtotheguenther @itorras13 Make sure to add `onSelect={event => event.preventDefault()}` to not close dropdown and move the dialog to inside of `Dropdown.Content`. 

https://codesandbox.io/p/sandbox/infallible-kate-rj6kuu

Additional examples https://codesandbox.io/s/dropdownmenu-dialog-items-r9sq1q?file=/src/App.js

**Comment by Nradar** [comment]
Have the same issue on dialog nested inside a context menu.

After context menu open, it applied `pointer-events: none;` to the body.
When the option is selected opens the dialog, the `pointer-events: none;` is removed.
When close dialog, the `pointer-events: none;` is applied again, which freeze everything on the page.

**Comment by xavhan** [comment]
Got the issue to with a button in a DropdownMenu opening in modal 
@joaom00 suggestion fixed the issue (added a e.preventDefault() in the onClick function)

**Comment by GFialho** [comment]
I fixed this problem very easily, you just have to pass this props to Dropdown Root:
```
                open={dropdownOpen}
                onOpenChange={setDropdownOpen}
```

And before opening the Dialog you have to close the dropdown:

```
    setDropdownOpen(false);
    setDialogOpen(true);
```

**Comment by hipstersmoothie** [comment]
I am hitting this too. It happens in this situation for me:

- open a menu
- click an item that triggers a Dialog
- close dialog as quickly as I can

From looking at the code it seems like in this situation the following is happening:

1. open menu => pointer events set to none
2. open dialog => menu closes, pointer events set to auto again
3. dialog closes => `originalBodyPointerEvents` is `none` because of menu

Now the whole page is "frozen"

**Comment by hipstersmoothie** [comment]
If I wrap the code in my menu item's onSelect in a rAF it works as expected

**Comment by hipstersmoothie** [comment]
Basically: if you want until the unmount happens on the menu to show the dialog it works

**Comment by benoitgrelard** [comment]
@hipstersmoothie, do you have a reproduction sandbox?
I am following your steps and cannot reproduce the issue you are mentioning: https://codesandbox.io/s/dropdownmenu-dialog-items-r9sq1q

**Comment by hipstersmoothie** [comment]
One more thing before I try to make a repro: I have a close animation on the menu. if I turn that off it also fixes the issue

**Comment by hipstersmoothie** [comment]
It has to do with exit animations https://codesandbox.io/s/dropdownmenu-dialog-items-forked-1kle9p?file=/src/styles.css

**Comment by hipstersmoothie** [comment]
Here is a video of it happening

Uploading CleanShot 2023-05-30 at 11.02.26.mp4…

**Comment by poojalodhi** [comment]
I am also facing the same issue, I am using @radix-ui/react-dropdown-menu:2.0.4 and @radix-ui/react-dialog: 1.0.4

**Comment by B2o5T** [comment]
I experienced the same issue while using the radix DropdownMenu and Dialog together

setting `modal={false}` on DropdownMenu.Root fixes it for me https://www.radix-ui.com/docs/primitives/components/dropdown-menu#root

**Comment by hai5nguy** [comment]
@B2o5T Same

**Comment by MatheusPires99** [comment]
Hey guys, I managed to fix this issue on my end by updating all Radix libraries to the latest versions, so if you're using a Tooltip, Popover, and other, try to update them all.

**Comment by uncvrd** [comment]
> It has to do with exit animations and not using the item as a trigger (common on our app, we want the menu closed when the item is clicked) https://codesandbox.io/s/dropdownmenu-dialog-items-forked-1kle9p?file=/src/styles.css

So I'm running in to the same problem but I _do_ use the item as a trigger, so I guess it comes down to some sort of race condition with the exit animation. I have a fairly quick exit animation and sometimes the `pointer-events` are removed properly and sometimes they are not...removing the animation fixes everything 🤷

**Comment by sljuka** [comment]
Also experiencing same issue as @B2o5T 
I am using a dropdown menu item which opens a Dialog on click. After closing the dialog I still have pointer-events none in body. Setting dropdown menu to modal={false} fixes this issue but this also means dropdown-menu is not a modal.

**Comment by sebi75** [comment]
This bug reproduces also for 
"@radix-ui/react-alert-dialog": "^1.0.4"
For a quick fix, downgrade to 1.0.3

**Comment by sljuka** [comment]
fixed after updating all used radix packages, not only `react-dialog` and `react-dropdown-menu` 🙌

**Comment by zachbresler21** [comment]
I'm experiencing the same issue with the pointer-events: none being added to the body even after closing the Alert Dialog. I don't use a trigger and rather trigger the alert to open to confirm an action. I add open and onOpenChange as props to the root and and use local state to update the state of the alert. "@radix-ui/react-alert-dialog": "^1.0.4"  - any idea when this will be fixed. Would prefer not to downgrade to 1.0.3 but obviously in the mean time I will. Thanks

**Comment by zachbresler21** [comment]
The issue actually persists on @radix-ui/react-alert-dialog": "1.0.3" as well 😞

**Comment by brandalx** [comment]
i had same error so i tried to solve my way and this actually work 
i did this by removing the style of pointer events like so:

`  onClose: () => {
    set({ type: null, isOpen: false });

    // Delay restoring pointer events for 2 seconds
    setTimeout(() => {
      document.body.style.pointerEvents = "auto";
    }, 1000);
  },
}));`

Note, i did it with small timeout to make sure that first all modal scripts are completed and then im manually removing that. Hope it helps!

**Comment by ericfrodriguez** [comment]
Updating "@radix-ui/react-alert-dialog" from "^1.0.4" to "^1.0.5" is working for this issue. Otherwise you can try removing pointer events styles from body in your onClose event like this way https://github.com/radix-ui/primitives/issues/1241#issuecomment-1734547434

**Comment by TranquilMarmot** [comment]
For us, this was being caused by a dialog being opened by a dropdown.

Two possible fixes for us were:
- Update `@radix-ui/react-dropdown-menu` to `2.0.6`
- Add `modal={false}` to the dropdowns

**Comment by robintown** [comment]
Oh, and now I've found these related issues: https://github.com/radix-ui/primitives/issues/1088 https://github.com/radix-ui/primitives/issues/2355

**Comment by imhoffd** [comment]
I am also running into this issue. I double-checked our bundle and confirmed that we only have one `@radix-ui/react-dismissable-layer` package. We are also on the latest versions of all Radix packages.

I forked @hipstersmoothie's codesandbox demo and updated the versions to demonstrate that it's still reproducible with the latest versions: https://codesandbox.io/p/sandbox/dropdownmenu-dialog-items-forked-94x39v?file=%2Fsrc%2FApp.js

Repro steps:
1. Click "Actions"
2. Click "Edit 2"
3. Click again quickly to dismiss the dialog before the dropdown menu exit animation is complete
4. Observe `pointer-events: none` still on body

I believe this is the best way to demonstrate the bug, although in our app we are seeing the bug occur with a dropdown within a dialog, both dismissed at the same time roughly equivalent exit animation durations.

@benoitgrelard Sorry for the ping, but we've seen this manifest in multiple ways (e.g dialog as child of dropdown, vice versa) and it does have a disastrous effect on the app as it renders it unresponsive to all pointer events. 

In the meantime, I am going to implement [this workaround](https://github.com/radix-ui/primitives/issues/1241#issuecomment-1734547434) (thanks @brandalx). This is what I ended up with in `Dialog.tsx` (just make sure the timeout is longer than your exit animations, but short enough to unfreeze your app before a user can interact):

```ts
  useEffect(() => {
    if (!open) {
      setTimeout(() => {
        document.body.style.pointerEvents = ''
      }, 500)
    }
  }, [open])
```

Thank you to the maintainers and contributors of Radix! We are thoroughly pleased thus far.

**Comment by mardausdennis** [comment]
> I forked @hipstersmoothie's codesandbox demo and updated the versions to demonstrate that it's still reproducible with the latest versions: https://codesandbox.io/p/sandbox/dropdownmenu-dialog-items-forked-94x39v?file=%2Fsrc%2FApp.js
> 
> Repro steps:
> 
> 1. Click "Actions"
> 2. Click "Edit 2"
> 3. Click again quickly to dismiss the dialog before the dropdown menu exit animation is complete
> 4. Observe `pointer-events: none` still on body
> 
> I believe this is the best way to demonstrate the bug, although in our app we are seeing the bug occur with a dropdown within a dialog, both dismissed at the same time roughly equivalent exit animation durations.
> 
> In the meantime, I am going to implement [this workaround](https://github.com/radix-ui/primitives/issues/1241#issuecomment-1734547434) (thanks @brandalx). This is what I ended up with in `Dialog.tsx` (just make sure the timeout is longer than your exit animations, but short enough to unfreeze your app before a user can interact):
> 
> ```ts
>   useEffect(() => {
>     if (!open) {
>       setTimeout(() => {
>         document.body.style.pointerEvents = ''
>       }, 500)
>     }
>   }, [open])
> ```

I'm experiencing the same issue in my project, though it happens with a popover inside a modal dialog. When I open the popover and then close the dialog, everything becomes unresponsive, just as you described.

The workaround you mentioned also works for me, but I agree it seems a bit hacky. It would be ideal to get this bug fixed properly as soon as possible, especially since I see it's been around for a while.

As developers, having these basic functions work reliably is crucial so we don't negatively impact the user experience. I hope the Radix devs can get this sorted out soon.

**Comment by JRhodes95** [comment]
Hey folks - just seconding that this appears to be an ongoing issue.

Don't have a perfect repro example but I'm using the dropdown as an actions menu on a table.
A 'delete' action triggers an alert dialog but when closing it the `pointer-events:none` remains on the body.
Have checked and all radix deps are up to date.

Appreciate your work on Radix but would be awesome if you could take a look at this one!

Thanks

**Comment by sturdynut** [comment]
Having this issue as well with the latest version.  To fix, I found that you can simply wire up the `onOpenChange` and update the body pointerEvents there.  See example below.

```
...
const handleOnOpenChange = (open: boolean) => {
    // Bug fix: Radix UI leaves pointer-events none on body when dialog is closed
    if (open === false) {
      document.body.style.pointerEvents = "auto";
    }
  };

  return (
    <Dialog.Root onOpenChange={handleOnOpenChange}>
...
```

**Comment by hwride** [comment]
In my case I have found this happens when you attach a close animation to the overlay, and that it also causes the overlay not to be removed. This doesn't happen without the close animation. Using version `1.0.5`.

**Comment by hwride** [comment]
Hi @benoitgrelard, should this one be re-opened? It seems it's still happening to quite a few people. Thanks.

**Comment by swiftpaca** [comment]
Hi @benoitgrelard, this is still an issue. Any updates/progress? Appreciate the help.

**Comment by Abduganeoff** [comment]
> I experienced the same issue while using the radix DropdownMenu and Dialog together
> 
> setting `modal={false}` on DropdownMenu.Root fixes it for me https://www.radix-ui.com/docs/primitives/components/dropdown-menu#root

I was also having the same issue with `Dialog` and `DropdownMenu`. you are just brilliant

**Comment by dalalRohit** [comment]
settings `modal={false}` on `<DropdownMenu />` solved it for me.

**Comment by K-Mistele** [comment]
Setting `modal={false}` doesn't work for me because the dialog closes instantly again - probably because I'm using it in conjunction with a dropdown menu. It seems like this is a regression?

**Comment by sahanatvessel** [comment]
why was this issue closed?

**Comment by sahanatvessel** [comment]
https://github.com/radix-ui/primitives/issues/1241

**Comment by sahanatvessel** [comment]
related https://github.com/radix-ui/primitives/issues/2122

**Comment by Notmeomg** [comment]
This issue was resolved for me by aligning my package versions. I did this after reading https://github.com/radix-ui/primitives/issues/1088.

**Comment by kacem22** [comment]
> > I forked @hipstersmoothie's codesandbox demo and updated the versions to demonstrate that it's still reproducible with the latest versions: https://codesandbox.io/p/sandbox/dropdownmenu-dialog-items-forked-94x39v?file=%2Fsrc%2FApp.js
> > Repro steps:
> > 
> > 1. Click "Actions"
> > 2. Click "Edit 2"
> > 3. Click again quickly to dismiss the dialog before the dropdown menu exit animation is complete
> > 4. Observe `pointer-events: none` still on body
> > 
> > I believe this is the best way to demonstrate the bug, although in our app we are seeing the bug occur with a dropdown within a dialog, both dismissed at the same time roughly equivalent exit animation durations.
> > In the meantime, I am going to implement [this workaround](https://github.com/radix-ui/primitives/issues/1241#issuecomment-1734547434) (thanks @brandalx). This is what I ended up with in `Dialog.tsx` (just make sure the timeout is longer than your exit animations, but short enough to unfreeze your app before a user can interact):
> > ```ts
> >   useEffect(() => {
> >     if (!open) {
> >       setTimeout(() => {
> >         document.body.style.pointerEvents = ''
> >       }, 500)
> >     }
> >   }, [open])
> > ```
> 
> I'm experiencing the same issue in my project, though it happens with a popover inside a modal dialog. When I open the popover and then close the dialog, everything becomes unresponsive, just as you described.
> 
> The workaround you mentioned also works for me, but I agree it seems a bit hacky. It would be ideal to get this bug fixed properly as soon as possible, especially since I see it's been around for a while.
> 
> As developers, having these basic functions work reliably is crucial so we don't negatively impact the user experience. I hope the Radix devs can get this sorted out soon.

it works for me thank you

**Comment by kacem22** [comment]
> For us, this was being caused by a dialog being opened by a dropdown.
> 
> Two possible fixes for us were:
> 
> * Update `@radix-ui/react-dropdown-menu` to `2.0.6`
> * Add `modal={false}` to the dropdowns (not needed if you update)

it works for me thank you

**Comment by HussainAhmadDev** [comment]
The simple Css solution is to just give `pointer-events: auto` to the other element that got broken due to the body `pointer-events: none` easy hack 😊

**Comment by jvenus99** [comment]
Hi Guys! 
I found a other solution for this problem. I just install a dependency `@radix-ui/react-dismissable-layer`
So, do `npm i @radix-ui/react-dismissable-layer` and rerun your project.

**Comment by Aslam97** [comment]
> Hi Guys! I found a other solution for this problem. I just install a dependency `@radix-ui/react-dismissable-layer` So, do `npm i @radix-ui/react-dismissable-layer` and rerun your project.

this does work if I remove node_modules and lock file.

**Comment by dytra** [comment]
In my case I'm using `<ContextMenu />` for triggering the dialog.
Setting the `modal` prop to `false` solves the issue
```javascript
<ContextMenu key={item.fileId} modal={false}>
...
</ContextMenu>
```

**Comment by Ghernouz** [comment]
What works for me was to set 
```
"@radix-ui/react-dialog": "1.1.1",
"@radix-ui/react-dismissable-layer": "1.1.1"
```

**Comment by Ghernouz** [comment]
What works for me was to setup:
```
    "@radix-ui/react-dialog": "1.1.1",
    "@radix-ui/react-dismissable-layer": "1.1.1",
```

**Comment by yuanbo07** [comment]
> What works for me was to clean packages and set
> 
> ```
> "@radix-ui/react-dialog": "1.1.1",
> "@radix-ui/react-dismissable-layer": "1.1.1"
> ```

I can confirm the issue is finally gone after adding react-dismissable-layer

**Comment by appinteractive** [comment]
Hey, we encountered the same issue when opening an `AlertDialog` from a `DropDown`. 

**TLDR:** add a tiny timeout before opening the alert and it works!

I digged a bit deeper and realized, that a scroll lock counter increased in the body. So I assume that the counter goes up (because two modals are open: Dropdown + Alert) but the timing is just a bit off, so while the dropdown is closing the counter stays wrongly to high. That way it assumes, that still at least one modal is open and so the scroll lock should persist until it's closed.

By applying a tiny dely before opening another modal, the issue is solved. In my testing even 0ms are enough, but for safety I use 50m and it's done. 

```jsx
const [isDialogOpen, setDialogOpen] = useState(false)

return (
  <>
    <Button onClick={() => setTimeout(() => setDialogOpen(true), 50)}>...</Button>
    
    <AlertDialog key='delete' open={isDialogOpen} onOpenChange={(open) => (!open && setDialogOpen(false))}>
    ...
    </AlertDialog>
  </>
);
```

**Comment by wave-m** [comment]
Hi @benoitgrelard, this is still an issue. Any updates/progress?

**Comment by joshdance** [comment]
I am hitting this bug. Not using Radix directly, I am using ShadcnUI. 

I have a DropdownMenu, in a Sidebar.

When I click on the DropdownMenu again to close it, it decrements the scroll lock to 1, then clicking outside the sidebar it goes to zero and the pointer-events: none; is removed. 

But when I just click outside the DropdownMenu, and outside the Sidebar, at the same time, to close it. It only decrements by 1, and the pointer-events: none incorrectly is still applied to the body, making it so I can't click on anything after that have to refresh the page. 

I tried applying the modal={false} to the DropdownMenu, but that just makes it so it doesn't appear at all.

What **did work** was getting all the @radix-ui/react-dismissable-layer to the same version. 1.1.3. That is what fixed it for me.

**Comment by appinteractive** [comment]
@joshdance have you upgraded all radix dependencies in your project? For us this was the key, also nuke your node_modules and install them again. This might help. With this, we were able to remove our [workaround](https://github.com/radix-ui/primitives/issues/1241#issuecomment-2462326355).

**Comment by cardoso-sj** [comment]
Fixed the pointer-events issue by adding proper event handling in the DialogContent component. 

The fix involves:
1. Adding `onCloseAutoFocus` event handler to the DialogPrimitive.Content component
2. Preventing the default focus behavior
3. Restoring the pointer-events style to its original state

Here's the relevant code change:

```tsx
<DialogPrimitive.Content
  // ... other props ...
  onCloseAutoFocus={(event) => {
    event.preventDefault();
    document.body.style.pointerEvents = '';
  }}
>
```

Shadcnui Dialog.tsx `DialogContent`
```tsx
const DialogContent = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Content>
>(({ className, children, ...props }, ref) => (
  <DialogPortal>
    <DialogOverlay />
    <DialogPrimitive.Content
      ref={ref}
      className={cn(
        "fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border bg-background p-6 shadow-lg duration-200 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%] data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%] sm:rounded-lg",
        className
      )}
      {...props}
      onCloseAutoFocus={(event) => {
        event.preventDefault();
        document.body.style.pointerEvents = '';
      }}
    >
      {children}
      <DialogPrimitive.Close className="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none data-[state=open]:bg-accent data-[state=open]:text-muted-foreground">
        <X className="h-4 w-4" />
        <span className="sr-only">Close</span>
      </DialogPrimitive.Close>
    </DialogPrimitive.Content>
  </DialogPortal>
))
DialogContent.displayName = DialogPrimitive.Content.displayName
```

**Comment by joshdance** [comment]
@appinteractive yep upgrading all the radix dependencies fixed this for me. thanks!

**Comment by param-codezz** [comment]
> Hey, we encountered the same issue when opening an `AlertDialog` from a `DropDown` programmatically. `@radix-ui/react-dismissable-layer` did not work for us.
> 
> **TLDR:** add a tiny timeout before opening the Alert (or any other modal based component) and it works!
> 
> I digged a bit deeper and realized, that a scroll lock counter increased in the body. So I assume that the counter goes up (because two modals are open: Dropdown + Alert) but the timing is just a bit off, so while the dropdown is closing the counter stays wrongly too high. That way it assumes, that still at least one modal is open and so the scroll lock should persist until it's closed.
> 
> By applying a tiny delay before opening another modal, the issue is solved. In my testing even 0ms are enough, but for safety I use 50m, and it's done.
> 
> const [isDialogOpen, setDialogOpen] = useState(false)
> 
> return (
>   <>
>     <Button onClick={() => setTimeout(() => setDialogOpen(true), 50)}>...</Button>
>     
>     <AlertDialog key='delete' open={isDialogOpen} onOpenChange={(open) => (!open && setDialogOpen(false))}>
>     ...
>     </AlertDialog>
>   </>
> );

worked for me, thanks, I think the issue still persists in the current version too.

**Comment by toandk** [comment]
> Fixed the pointer-events issue by adding proper event handling in the DialogContent component.
> 
> The fix involves:
> 
> 1. Adding `onCloseAutoFocus` event handler to the DialogPrimitive.Content component
> 2. Preventing the default focus behavior
> 3. Restoring the pointer-events style to its original state
> 
> Here's the relevant code change:
> 
> <DialogPrimitive.Content
>   // ... other props ...
>   onCloseAutoFocus={(event) => {
>     event.preventDefault();
>     document.body.style.pointerEvents = '';
>   }}
> >
> Shadcnui Dialog.tsx `DialogContent`
> 
> const DialogContent = React.forwardRef<
>   React.ElementRef<typeof DialogPrimitive.Content>,
>   React.ComponentPropsWithoutRef<typeof DialogPrimitive.Content>
> >(({ className, children, ...props }, ref) => (
>   <DialogPortal>
>     <DialogOverlay />
>     <DialogPrimitive.Content
>       ref={ref}
>       className={cn(
>         "fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border bg-background p-6 shadow-lg duration-200 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%] data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%] sm:rounded-lg",
>         className
>       )}
>       {...props}
>       onCloseAutoFocus={(event) => {
>         event.preventDefault();
>         document.body.style.pointerEvents = '';
>       }}
>     >
>       {children}
>       <DialogPrimitive.Close className="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none data-[state=open]:bg-accent data-[state=open]:text-muted-foreground">
>         <X className="h-4 w-4" />
>         <span className="sr-only">Close</span>
>       </DialogPrimitive.Close>
>     </DialogPrimitive.Content>
>   </DialogPortal>
> ))
> DialogContent.displayName = DialogPrimitive.Content.displayName

worked for me. Thanks!

**Comment by joeyfigaro** [comment]
> Fixed the pointer-events issue by adding proper event handling in the DialogContent component.
> 
> The fix involves:
> 
> 1. Adding `onCloseAutoFocus` event handler to the DialogPrimitive.Content component
> 2. Preventing the default focus behavior
> 3. Restoring the pointer-events style to its original state
> 
> Here's the relevant code change:
> 
> <DialogPrimitive.Content
>   // ... other props ...
>   onCloseAutoFocus={(event) => {
>     event.preventDefault();
>     document.body.style.pointerEvents = '';
>   }}
> >
> Shadcnui Dialog.tsx `DialogContent`
> 
> const DialogContent = React.forwardRef<
>   React.ElementRef<typeof DialogPrimitive.Content>,
>   React.ComponentPropsWithoutRef<typeof DialogPrimitive.Content>
> >(({ className, children, ...props }, ref) => (
>   <DialogPortal>
>     <DialogOverlay />
>     <DialogPrimitive.Content
>       ref={ref}
>       className={cn(
>         "fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border bg-background p-6 shadow-lg duration-200 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%] data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%] sm:rounded-lg",
>         className
>       )}
>       {...props}
>       onCloseAutoFocus={(event) => {
>         event.preventDefault();
>         document.body.style.pointerEvents = '';
>       }}
>     >
>       {children}
>       <DialogPrimitive.Close className="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none data-[state=open]:bg-accent data-[state=open]:text-muted-foreground">
>         <X className="h-4 w-4" />
>         <span className="sr-only">Close</span>
>       </DialogPrimitive.Close>
>     </DialogPrimitive.Content>
>   </DialogPortal>
> ))
> DialogContent.displayName = DialogPrimitive.Content.displayName

This is not working, unfortunately – for others looking.

**Comment by dinesh8368** [comment]
Solution that worked for me: **Upgraded the Radix packages to the latest version.**

**Comment by n0neye** [comment]
Seemed to be related to this one: https://github.com/radix-ui/primitives/issues/1088
I got it working by upgrading dismissable-layer related modules, deleting the node_modules folder, and reinstalling the project.


> "@radix-ui/react-dropdown-menu": "2.1.4",
"@radix-ui/react-select": "2.1.4",
"@radix-ui/react-popover": "1.1.4",
"@radix-ui/react-dialog": "1.1.4",
"overrides": {
  "@radix-ui/react-dismissable-layer": "1.1.4"
}

**Comment by zubair-kl** [comment]
<DialogPrimitive.Content
// ... other props ...
onCloseAutoFocus={(event) => {
event.preventDefault();
document.body.style.pointerEvents = '';
}}

i used this and it fixed the issue. thanks gus

**Comment by dlo** [comment]
It's pretty insane that this is still an issue.

1. Open modal.
2. Close modal.
3. Entire UI is broken.

**Comment by dlo** [comment]
@joshdance This was tested on @radix-ui/react-dialog v1.1.14, which is the latest version on npm.

<img width="1196" height="1013" alt="Image" src="https://github.com/user-attachments/assets/4f4f2c4f-b34b-44fa-80ae-0cfa9c2b9562" />

**Comment by abdullahceylan** [comment]
This issue occurs because of a conflict between the modal and another modal supported component you’re using to trigger it, most likely a dropdown. To fix it, simply add `modal={false}` to the trigger component.

**Comment by HussainAhmadDev** [comment]
@ziyadkhalil The simple css solution is to just give pointer-events: auto to the other element that got broken due to the body pointer-events: none easy hack 😊

**Comment by ub-octogonn** [comment]
At that day, I do personally still experience the issue. I have got a drawer component ( from vaul, via shadcn UI ) and a confirm dialog component based on @radix-ui/react-alert-dialog based component.
First the confirm dialog opens, when clicking confirm it opens the drawer after the confirm dialog closes.
Then after closing the drawer, the pointer-events: none is set at the body level right after. 

Of course we could override manually the body.style.pointerEvents to auto after the drawer has closed, but its not a clean solution. We need a standard and clean way to fix it

**Comment by ChristianPerrotta** [comment]
> This issue occurs because of a conflict between the modal and another modal supported component you’re using to trigger it, most likely a dropdown. To fix it, simply add `modal={false}` to the trigger component.

This is the correct solution, by @abdullahceylan! Please stop messing with css directly and use this instead!

**Comment by mttetc** [comment]
The fix is really simple, ditch radix and use base, base ui has been released in v1 and shadcn supports it.
https://ui.shadcn.com/create?base=base and then open in V0 and migrate your stuff.

**Comment by SuddyN** [comment]
Still occurs on @radix-ui/react-dialog v1.1.15

Used this fix: https://github.com/radix-ui/primitives/issues/1241#issuecomment-2589438039

**Comment by brianlyn** [comment]
Can confirm still occurs with `@radix-ui/react-dialog v1.1.15` when a dialog is triggered from a dropdown menu. Fixed by setting `modal={false}` on the dropdown.
