### ISSUE TITLE
[Popover] [Dialog] When nesting `Popover` in `Dialog`, clicks in the `Popover` are closing it

### ISSUE THREAD

**Issue by williamhzo** [radix-ui/primitives#2121]
### Current Behavior

When nesting `Popover` in `Dialog`, clicks in the `Popover` are closing it (considered outside interaction) even with the appropriate z-indices.

### Expected behavior

When opening the `Popover` from the `Dialog`, interaction within the `Popover` shouldn't trigger an outside click and therefore shouldn't close it.

### Reproducible example

https://codesandbox.io/s/mystifying-banzai-v59705?file=/src/App.tsx

### Suggested solution

Adding the `modal` prop to the `Popover` root seems to fix it, but then outside content remains blocked and un-interactive when dismissing the `Dialog` + `Popover` by an outside click.

### Additional context

i assume it's a portal and z-index issue, but what i understood is that radix is supposed to natively handle such nesting?

i'm certainly missing something here, as this use-case seems pretty common, i tried searching in other issues but didn't find an answer to this. 

thanks in advance for the support! you (the whole team + maintainers) are doing an amazing job 🙏

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     `react-popover`, `react-dialog`    |     resp. `1.0.5`, `1.0.3`    |
| React            |  n/a    |   `18.2.0`      |
| Browser          |     Arc    |   `0.101.2`      |
| Assistive tech   |     n/a    |    n/a     |
| Node             | n/a     |     `16.17`    |
| yarn         |     n/a    |    `1.22.19`     |
| Operating System |    macOS     |   `13.3.1`      |

**Comment by joaom00** [comment]
Hey @williamhzo,

It's an issue when components use different versions of the `DismissableLayer` component under the hood. https://github.com/radix-ui/primitives/issues/1088 

In your example, updating the `Dialog` to the latest version fixes the issue.

**Comment by williamhzo** [comment]
thanks for the explanation, that fixes the reproduction CodeSandbox mentioned in the issue description but it doesn't seem to fix in my actual project, i just checked the versions and both packages are at their latest: 

- `@radix-ui/react-dialog` → `^1.0.3` 
- `@radix-ui/react-popover` → `^1.0.5`

and running `yarn info` on both packages and both have the `@radix-ui/react-dismissable-layer` to `1.0.3`.

i know it's a long shot since you can't reproduce on your end but do you know of any issues that might cause this? i tried re-installing the deps and upgrading to latest but wasn't successful.

thanks in advance!

**Comment by williamhzo** [comment]
for anyone having the issue, i think i've may've found the cause of the bug: another 3rd party lib is using an outdated version of `@radix-ui/react-dismissable-layer` under the hood, causing the version mismatch. 

enforcing the correct version with yarn [`resolutions`](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-how-to-use-it) doesn't seem to work, apparently due to my yarn version being version `1.x.x` (it seems that [only v2 and v3 supports `"/"`](https://github.com/yarnpkg/yarn/issues/4874)).

**Comment by williamhzo** [comment]
peer dependency was upgraded to latest version, closing the issue as it's now fixed.

thanks again @joaom00!

**Comment by taoliujun** [comment]
I can't solve it even I put resolutions in package.json.

`
// package.json
"dependencies": {
  "@radix-ui/react-dialog": "1.0.5-rc.5",
  "@radix-ui/react-popover": "1.0.7-rc.5",
},
 "resolutions": {
        "@radix-ui/react-dismissable-layer": "1.0.5-rc.5"
    },
`

**Comment by williamhzo** [comment]
hey @taoliujun, you appear to be using the release candidate versions of `@radix-ui/react-dialog` and `@radix-ui/react-popover`, if you update to latest stable version the issue should be fixed, with no resolution needed

**Comment by zain-adtracktiv** [comment]
Hey, this is still happening for me with the latest version (1.1.1) of both the @radix-ui/react-popover and @radix-ui/react-dialog

**Comment by roodiroot** [comment]
Set the modal prop to true on the Popover root.
https://www.radix-ui.com/primitives/docs/components/popover#api-reference

> Hey, this is still happening for me with the latest version (1.1.1) of both the @radix-ui/react-popover and @radix-ui/react-dialog

**Comment by ASgmbv** [comment]
`
const [container, setContainer] = useState(null);

<Dialog>
        <DialogTrigger asChild>
          <Button>Logic Logic</Button>
        </DialogTrigger>
        <DialogContent>
         <div ref={setContainer}></div>

          <Popover>
            <PopoverTrigger asChild>
              <Button>
                Set condition
              </Button>
            </PopoverTrigger>
            <PopoverContent container={container}> // need to make it accept container prop
              <Input />
            </PopoverContent>
          </Popover>
        </DialogContent>
      </Dialog>
`

**Comment by fgatti675** [comment]
Hi, facing the same issue.
This seems not to be a valid prop?
```
<PopoverContent container={container}>
```
Thank you

**Comment by fgatti675** [comment]
Btw, making the PopOver modal fixed the issue for me :)
    ```<PopoverPrimitive.Root modal={true}>```

**Comment by Ssalvador221** [comment]
> Btw, making the PopOver modal fixed the issue for me :) `<PopoverPrimitive.Root modal={true}>`

This worked for me too! Thanks, @fgatti675.

**Comment by schcolnikj** [comment]
> Set the modal prop to true on the Popover root. https://www.radix-ui.com/primitives/docs/components/popover#api-reference
> 
> > Hey, this is still happening for me with the latest version (1.1.1) of both the @radix-ui/react-popover and @radix-ui/react-dialog

Can this action make the page unresponsive when closing the popover / dialog?

It's happening something of this sort, but I have already updated react-dialog and react-popover to their last version (1.1.2). 
https://github.com/radix-ui/primitives/issues/1241

**Comment by thuansb** [comment]
> Assignees
> No one assigned
> Labels
> None yet
> Projects
> None yet
> Milestone
> No milestone
> Development
> No branches or pull requests
> 
> 
> Notifications
> Customize
> 
> Subscribe
> You’re not receiving notifications from this thread.
> 
> 8 participants
> [ <img alt="@fgatti675" width="26" height="26" src="https://avatars.githubusercontent.com/u/5120271?s=52&amp;v=4"> ](/fgatti675) [ <img alt="@taoliujun" width="26" height="26" src="https://avatars.githubusercontent.com/u/5689134?s=52&amp;v=4"> ](/taoliujun) [ <img alt="@ASgmbv" width="26" height="26" src="https://avatars.githubusercontent.com/u/38725027?s=52&amp;v=4"> ](/ASgmbv) [ <img alt="@joaom00" width="26" height="26" src="https://avatars.githubusercontent.com/u/48808846?s=52&amp;v=4"> ](/joaom00) [ <img alt="@williamhzo" width="26" height="26" src="https://avatars.githubusercontent.com/u/49357401?s=52&amp;v=4"> ](/williamhzo) [ <img alt="@Ssalvador221" width="26" height="26" src="https://avatars.githubusercontent.com/u/82125523?s=52&amp;v=4"> ](/Ssalvador221) [ <img alt="@roodiroot" width="26" height="26" src="https://avatars.githubusercontent.com/u/86611761?s=52&amp;v=4"> ](/roodiroot) [ <img alt="@zain-adtracktiv" width="26" height="26" src="https://avatars.githubusercontent.com/u/164865068?s=52&amp;v=4"> ](/zain-adtracktiv)
> ## Footer
> [ ](https://github.com)
> © 2025 GitHub, Inc.
> ### Footer navigation

Worked, but the <Input> component not clickable and when the dialog close, all elements on the page not clickable.
So I reverted the version from 1.1.4 to "@radix-ui/react-popover": "1.1.2" then it worked fine.

**Comment by thuansb** [comment]
> Btw, making the PopOver modal fixed the issue for me :) `<PopoverPrimitive.Root modal={true}>`

It worked, but there are some issues:

The Input component in the popover is not clickable.
When the popover and dialog are closed, none of the elements on the parent page are clickable.
So, I reverted the version from 1.1.4 to @radix-ui/react-popover: 1.1.2, and it worked fine.

**Comment by yashasvi-jain** [comment]
I have been trying to troubleshoot this issue for a minute and I am not sure what I am missing. However, I do have a bit of a different situation. I am using the `shadcn Command` component (`cmdk` under the hood) in a Dialog. I have a popover with an input in this command component and I could not get it to click. In a nutshell, I am trying to make a Command search component with filters.

I have set modal to true `Popover.Root`, but the input does not work i.e. I can't click it.

```
├─┬ @radix-ui/react-alert-dialog@1.1.2
│ └─┬ @radix-ui/react-dialog@1.1.2
│   └── @radix-ui/react-dismissable-layer@1.1.1
├─┬ @radix-ui/react-context-menu@2.2.2
│ └─┬ @radix-ui/react-menu@2.1.2
│   └── @radix-ui/react-dismissable-layer@1.1.1
├─┬ @radix-ui/react-dialog@1.1.6
│ └── @radix-ui/react-dismissable-layer@1.1.5
├─┬ @radix-ui/react-dropdown-menu@2.0.6
│ └─┬ @radix-ui/react-menu@2.0.6
│   └── @radix-ui/react-dismissable-layer@1.0.5
├─┬ @radix-ui/react-hover-card@1.0.7
│ └── @radix-ui/react-dismissable-layer@1.0.5
├─┬ @radix-ui/react-navigation-menu@1.2.1
│ └── @radix-ui/react-dismissable-layer@1.1.1
├─┬ @radix-ui/react-popover@1.1.2
│ └── @radix-ui/react-dismissable-layer@1.1.1
├─┬ @radix-ui/react-select@2.0.0
│ └── @radix-ui/react-dismissable-layer@1.0.5
├─┬ @radix-ui/react-toast@1.1.5
│ └── @radix-ui/react-dismissable-layer@1.0.5
├─┬ @radix-ui/react-tooltip@1.0.7
│ └── @radix-ui/react-dismissable-layer@1.0.5
└─┬ cmdk@0.2.0
  └─┬ @radix-ui/react-dialog@1.0.0
    └── @radix-ui/react-dismissable-layer@1.0.0
```

**Comment by TserenpuntsagZorigt** [comment]
Im facing same issue when using shadcn.
i reverted back to dialog and the popover both to 1.1.2 and set the popovers content pointer events to css.

**Comment by yashasvi-jain** [comment]
> Im facing same issue when using shadcn. i reverted back to dialog and the popover both to 1.1.2 and set the popovers content pointer events to all. this fixes the issue for now.

This doesn't seem to work for me :(. Also what do you mean by "pointer events to all"? Thanks for the help in advance!

```typescript
<PopoverContent className="!pointer-events-auto w-[200px] p-0">
```

**Comment by yashasvi-jain** [comment]
> Im facing same issue when using shadcn. i reverted back to dialog and the popover both to 1.1.2 and set the popovers content pointer events to auto. this fixes the issue for now.

Unfortunately, this does not seem to be working for me.

```typescript
<PopoverContent className="pointer-events-auto w-[200px] p-0">
        <Command>
          {showInput && <CommandInput className="pointer-events-auto" placeholder="Search..." />}
```

Am I doing something wrong? Thanks for the help in advance!

**Comment by nxn-nicole** [comment]
> Im facing same issue when using shadcn. i reverted back to dialog and the popover both to 1.1.2 and set the popovers content pointer events to auto. this fixes the issue for now.

Thank you! I also fixed my issue with this

**Comment by Alexis-Bize** [comment]
> > I have been trying to troubleshoot this issue for a minute and I am not sure what I am missing. However, I do have a bit of a different situation. I am using the `shadcn Command` component (`cmdk` under the hood) in a Dialog. I have a popover with an input in this comman.....
> 
> [@yashasvi-jain](https://github.com/yashasvi-jain) did you find a solution? i'm having the same issue?

I was able to resolve the issue by monkey-patching my dialog component with the following effect.

```javascript
useEffect(() => {
    return () => {
        setTimeout(() => {
            document.body.style.pointerEvents = '';
        }, 0);
    };
}, []);
```

**Comment by TserenpuntsagZorigt** [comment]
> > > Btw, making the PopOver modal fixed the issue for me :) `<PopoverPrimitive.Root modal={true}>`
> > 
> > 
> > It worked, but there are some issues:
> > The Input component in the popover is not clickable. When the popover and dialog are closed, none of the elements on the parent page are clickable. So, I reverted the version from 1.1.4 to @radix-ui/react-popover: 1.1.2, and it worked fine.
> 
> I was able to resolve the issue by monkey-patching the dialog with the following effect.
> 
> ```
> useEffect(() => {
>     return () => {
>         setTimeout(() => {
>             document.body.style.pointerEvents = '';
>         }, 0);
>     };
> }, []);
> ```

Hi alex this might sound dumb but this issue popped back for me i deleted node modules along with the package json lock and bumped up the versions tp the latest im guessing there were some peer dependencies that was depending on the version that was brokennand conflicting

**Comment by JAWS-tm** [comment]
I encountered the same issue when using the **shadcn** combobox (which uses `cmdk` under the hood). With `modal={true}`, click functionality behaved as expected, but the input focus problem persisted. 

Upgrading both `@radix-ui/react-dialog` and `@radix-ui/react-popover` to version `1.1.7` ultimately resolved the focus issue.

**Comment by yechukim** [comment]
i fixed this issue to use `container` prop in Popover 
just pass the modal element as container 

my version 
```
   "@radix-ui/react-popover": "^1.1.13"
    "@radix-ui/react-dialog": "^1.1.13",
```

```

```
