### ISSUE TITLE
Maximum update depth exceeded error with hover card

### ISSUE THREAD

**Issue by resthedev** [radix-ui/primitives#2717]
### Current Behavior

![image](https://github.com/radix-ui/primitives/assets/82852973/b29f5b36-28a0-457e-857e-aae8fd82a3bd)

Been banging my head against the wall with this one, so maybe someone has an idea on how to fix this.

Here is the full error stack trace: 
```
Unhandled Runtime Error
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

Call Stack
throwIfInfiniteUpdateLoopDetected
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (26657:10)
throwIfInfiniteUpdateLoopDetected
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (7679:2)
getRootForUpdatedFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (7570:9)
enqueueConcurrentHookUpdate
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (12929:15)
onAnchorChange
node_modules/@radix-ui/react-popper/dist/index.mjs (62:16)
create
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (21035:22)
commitHookEffectListMount
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23088:6)
commitHookPassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23193:10)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23190:8)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23304:8)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23190:8)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23190:8)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23304:8)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23190:8)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23190:8)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23304:8)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23190:8)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23304:8)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23304:8)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23190:8)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23190:8)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23304:8)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23190:8)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23304:8)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23190:8)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23190:8)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23304:8)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23190:8)
commitPassiveMountOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23171:6)
recursivelyTraversePassiveMountEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23190:8)
```
I am getting this error primarily when I am using the Radix hover card with code that re-renders frequently (in my case, `react-query`). This can be seen in the minimal reproduction linked later in this post. As `react-query`'s useQuery hook rerenders its parent, it causes the HoverCard to mount and rerender, causing the error. I've tried to memoize the hover card, but this did not fix the issue.

### Expected behavior

Error should not occur

### Reproducible example

[CodeSandbox Reproduction](https://codesandbox.io/p/sandbox/strange-architecture-htrqjt?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsvenp1m00063b6nvmx931co%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsvenp1m00023b6noss784ud%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsvenp1m00033b6n9w4wygf5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsvenp1m00053b6n3ut42a9c%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsvenp1m00023b6noss784ud%2522%253A%257B%2522id%2522%253A%2522clsvenp1m00023b6noss784ud%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clsvenp1m00053b6n3ut42a9c%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsvenp1m00043b6njvypbyww%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsvenp1m00053b6n3ut42a9c%2522%252C%2522activeTabId%2522%253A%2522clsvenp1m00043b6njvypbyww%2522%257D%252C%2522clsvenp1m00033b6n9w4wygf5%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsvenp1m00033b6n9w4wygf5%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A17.126200274348406%257D)

**Steps to reproduce**

1. Open `Preview console` in the CodeSandbox

![CleanShot 2024-02-20 at 23 31 13@2x](https://github.com/radix-ui/primitives/assets/82852973/1827bee1-e04b-412c-80de-8c5e20552fb5)

2. Refresh the CodeSandbox window

![CleanShot 2024-02-20 at 23 32 08@2x](https://github.com/radix-ui/primitives/assets/82852973/6a6588e0-7fcf-42e9-a5f2-eade60c7d00e)

3. Note the error in the console

### Suggested solution

It seems to be related to the `onAnchorChange` function call, but i'm not sure precisely how to solve this or where the root problem is (the library or my code).

### Additional context
No error is thrown if I only render a few buttons. Seems like React has a built in max limit before it throws an error. 
For my use case where I need to render 50-100 items at once with a hover card for each item, this error is a breaking issue. 

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-hover-card     |    latest     |
| React            | n/a     |    latest     |
| Browser          |    Arc     |    latest     |
| Assistive tech   |         |         |
| Node             | n/a     |     latest    |
| npm/yarn         |         |    latest     |
| Operating System |   Mac OS Sonoma      |     latest    |

**Comment by benoitgrelard** [comment]
I see some other warning:
<img width="584" alt="CleanShot 2024-02-29 at 13 03 32@2x" src="https://github.com/radix-ui/primitives/assets/1539897/730fabbe-ac4b-42c0-97f1-66943f4f70b6">

It's unlikely to be an issue with the primitive, but rather with the specific setup.

I will close the issue now, but feel free to keep chatting if you have more info to present.

**Comment by resthedev** [comment]
> I see some other warning: <img alt="CleanShot 2024-02-29 at 13 03 32@2x" width="584" src="https://private-user-images.githubusercontent.com/1539897/308932019-730fabbe-ac4b-42c0-97f1-66943f4f70b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNDI2NDYsIm5iZiI6MTcwOTM0MjM0NiwicGF0aCI6Ii8xNTM5ODk3LzMwODkzMjAxOS03MzBmYWJiZS1hYzRiLTQyYzAtOTdmMS02Njk0M2Y0ZjcwYjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDJUMDExOTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjkxYWY4NDIxNWZlMWRhYjc1OWNkYWQ0ZWZlMzBmYzlhMDAxNGZlZDRiZDBmMTI4MzQyNWQxZGFhOGZmN2UwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.K-Eg9SSIfOQpdMQRT-cksRMUzZPmtJg49f_6UaQRH3A">
> 
> It's unlikely to be an issue with the primitive, but rather with the specific setup.
> 
> I will close the issue now, but feel free to keep chatting if you have more info to present.

Hi @benoitgrelard — thanks for responding.
I was going off of the official radix-ui/primitives CodeSandbox template provided when I made this bug report. 
I switched to createroot and it seems to address the issue. 

I am using NextJS in my own application (where I am encountering the issue), so I could not make the same createRoot change there. I'm wondering if it's a clue though that something in my setup may be causing the issue.

**Comment by mwaterman29** [comment]
I'm getting this as well in Next - the only useful info to debug is that popper appears in the call stack:
![image](https://github.com/radix-ui/primitives/assets/37488563/81186ced-7d2a-4bae-972f-84e1586e9713)

I also have a popover that re-renders frequently, and then causes this error. This does seem like an issue with the primitive.

**Comment by thefathdev** [comment]
I am also getting this issue when using Popover 
![image](https://github.com/radix-ui/primitives/assets/102936904/987882f4-794e-4070-8e94-4830f5660904)

**Comment by wintercounter** [comment]
Same here, for me, it happens when I'm resizing the window.

**Comment by shubham-giraft** [comment]
Happened to me on a page where I was using 50+ popovers.

**Comment by mwaterman29** [comment]
Something is definitely not right here.
![image](https://github.com/user-attachments/assets/e7ee2046-2975-48c2-8d96-e3e7ea058673)

I have a common component for navigation buttons with a tooltip. I've got probably 4-6 of these on screen at a time, and occasional re-renders cause this error with a huge depth.

**Comment by resthedev** [comment]
Glad I'm not alone. This is not an actual fix but for my own purposes I've just wrapped my component in an error boundary for now so that it doesn't bubble up and crash the entire application. 

Hopefully this can be properly fixed though.

**Comment by TobxD** [comment]
I am also experiencing this with many HoverCards that re-render often. Would appreciate any pointers to fix this!

**Comment by resthedev** [comment]
@benoitgrelard Would we be able to reopen this issue as it seems like many others are also experiencing the same bug. Thank you!

**Comment by gonggqing** [comment]
Got similar issue when using Radix-ui dropdown menu with Next.js. Please take a look at this! @benoitgrelard The console report Maximum update depth exceeded too.

**Comment by Randulfe** [comment]
Having the same issue with Nextjs + Radix + reactflow when a context menu wraps over the nodes and the nodes start being dragged

**Comment by IvanSmiths** [comment]
Did anyone found some workaround? I am getting this error also with the `DropdownMenu.Trigger` primitive with Next.js each time I do an api call

**Comment by Randulfe** [comment]
@benoitgrelard any ideas or will this issue be reopened as it seems to be a recurring issue?

**Comment by Pipe-Runner** [comment]
I suddenly started getting this error out of no where. The popover worked fine a few months back and now all of a sudden I am getting this. 
![image](https://github.com/user-attachments/assets/aff56ae5-92b8-4e30-8bdb-e8ac3ad8c72b)

**Comment by Szuszi** [comment]
Also experiencing this when using Radix Dialog that has a material UI Popover or Select component inside:

<img width="421" alt="image" src="https://github.com/user-attachments/assets/2dc6c2ac-62fb-4336-b057-4f98255e6d77" />

**Comment by Pipe-Runner** [comment]
> Also experiencing this when using Radix Dialog that has a material UI Popover or Select component inside:
> 
> <img alt="image" width="421" src="https://private-user-images.githubusercontent.com/61591712/396545293-2dc6c2ac-62fb-4336-b057-4f98255e6d77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MjYxMzksIm5iZiI6MTczNDcyNTgzOSwicGF0aCI6Ii82MTU5MTcxMi8zOTY1NDUyOTMtMmRjNmMyYWMtNjJmYi00MzM2LWIwNTctNGY5ODI1NWU2ZDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDIwMTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNjIxZjNjY2RkN2JmZDFmMzQ1OGJhMTEwYzM0YzFmN2Y5MTQyMDMwZGIyZTY0MTIzN2VkY2MxMDgyM2JiOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HRXzAPDqNXne-e8BIi37A4eaN_v0TMyPkY5iI5MjlaM">

I am actually considering switching to Daisy UI instead of using Shadcn because of this. This is a UI breaking bug. And seems like there is no activity on this.

**Comment by gonggqing** [comment]
> > Also experiencing this when using Radix Dialog that has a material UI Popover or Select component inside:
> 
> > 
> 
> > <img alt="image" width="421" src="https://private-user-images.githubusercontent.com/61591712/396545293-2dc6c2ac-62fb-4336-b057-4f98255e6d77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MjYxMzksIm5iZiI6MTczNDcyNTgzOSwicGF0aCI6Ii82MTU5MTcxMi8zOTY1NDUyOTMtMmRjNmMyYWMtNjJmYi00MzM2LWIwNTctNGY5ODI1NWU2ZDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDIwMTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNjIxZjNjY2RkN2JmZDFmMzQ1OGJhMTEwYzM0YzFmN2Y5MTQyMDMwZGIyZTY0MTIzN2VkY2MxMDgyM2JiOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HRXzAPDqNXne-e8BIi37A4eaN_v0TMyPkY5iI5MjlaM">
> 
> 
> 
> I am actually considering switching to Daisy UI instead of using Shadcn because of this. This is a UI breaking bug. And seems like there is no activity on this.

At the first glance I thought was due to my misuses of useEffect, but after reviewing people's comments, looks like it's not my fault🥲. It takes me a while to end up here ...

**Comment by Pipe-Runner** [comment]
Folks, I upgraded my react version to the latest minor version of major version 18. This seems to have been fixed since then. Give it a try.

**Comment by kevingyang** [comment]
any updates here? on react 19.0.0 (latest), still happening, so unfortunately no option to upgrade

**Comment by Harukisatoh** [comment]
I have the same error using a DropdownMenu.

**Comment by IvanSmiths** [comment]
> I have the same error using a DropdownMenu.

Are you using React 19? To me worked out downgrading to React 18

**Comment by Strernd** [comment]
I am encountering the same problem when using a few dozen Popovers. @benoitgrelard pleas consider reopening this issue as this doesn't seems to have something todo with the setup you mentioned.

**Comment by vipafutu** [comment]
Having the same problem with several popovers as well. Using react 18.3.1 and NextJS 14.

**Comment by Randulfe** [comment]
@benoitgrelard bunch of others facing the same issue, please reconsider reopening or opening a new one. Should be investigated and should be compatible with React 19

**Comment by holoiii** [comment]
+1 to this, exact same issue

**Comment by efitzkiwi** [comment]
This also happens with the Collapsible component, I highly recommend migrating to ark-ui primitives as I've had nothing but problems with radix unfortunately

**Comment by Randulfe** [comment]
Ive created this issue to reopen this as so many of us are still experiencing this issue even with the latest versions: https://github.com/radix-ui/primitives/issues/2717

On the meanwhile, has anyone found a workaround?

**Comment by Harukisatoh** [comment]
Someone please give attention to this issue, this is open since February 2024.

**Comment by darklight9811** [comment]
I'm having this issue using this code:

```
import { Check, ChevronsUpDown } from "lucide-react";
import * as React from "react";

import { PopoverTrigger } from "@radix-ui/react-popover";
import { useControllableState } from "@radix-ui/react-use-controllable-state";
import { CommandLoading } from "cmdk";
import { cn } from "../../lib/utils";
import { Button } from "./button";
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "./command";
import { Popover, PopoverContent } from "./popover";

interface Props {
	t?: {
		placeholder: string;
		empty: string;
		loading: string;
	};

	value?: string;
	onChange?: (value: string) => void;
	onTextChange?: (text: string) => void;
	loading?: boolean;
	creatable?: boolean;
	prefix?: React.ReactNode;
	className?: string;
	options?: {
		id?: string;
		name?: string;
		value: string;
		label?: React.ReactNode;
	}[];
}

export function Combobox(props: Props) {
	const [open, setOpen] = React.useState(false);
	const [text, settext] = React.useState("");
	const [value, setValue] = useControllableState({
		prop: props.value,
		defaultProp: "",
		onChange: props.onChange,
	});

	const options = React.useMemo(() => {
		return (
			props.options?.map((option) => ({
				value: option.id || option.value || option.label,
				label: option.name || option.label || option.value,
			})) || []
		).concat(text ? [{ value: text, label: text }] : []);
	}, [props.options, text]);

	return (
		<Popover open={open} onOpenChange={setOpen}>
			<PopoverTrigger asChild>
				<Button
					variant="outline"
					aria-expanded={open}
					className={cn("w-full justify-between px-2", props.className)}
					onClick={() => setOpen(!open)}
				>
					<span className="flex gap-2 items-center">
						{props.prefix}
						{value ? (
							options.find((option) => option.value === value)?.label
						) : (
							<span>{props.t?.placeholder || ""}</span>
						)}
					</span>
					<ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
				</Button>
			</PopoverTrigger>
			<PopoverContent className="w-full p-0">
				<Command shouldFilter={false}>
					<CommandInput
						placeholder={props.t?.placeholder}
						onValueChange={(value) => {
							if (props.creatable) settext(value);
							props.onTextChange?.(value);
						}}
					/>
					<CommandEmpty>{props.t?.empty}</CommandEmpty>
					{(!props.options || props.loading) && props.t?.loading && (
						<CommandLoading>{props.t.loading}</CommandLoading>
					)}
					<CommandList>
						<CommandGroup>
							{options.map((option) => (
								<CommandItem
									key={option.value as string}
									value={option.value as string}
									className="gap-2 justify-between"
									onSelect={(currentValue) => {
										const select = currentValue === value ? "" : currentValue;
										setValue(select);
										setOpen(false);
									}}
								>
									<div className="flex gap-2 items-center">{option.label}</div>
									<Check
										className={cn("h-4 w-4", value === option.value ? "opacity-100" : "opacity-0")}
									/>
								</CommandItem>
							))}
						</CommandGroup>
					</CommandList>
				</Command>
			</PopoverContent>
		</Popover>
	);
}

```

the imports are shadcn related, so you can just import its components

**Comment by darklight9811** [comment]
this is the error stacktrace from react:

![Image](https://github.com/user-attachments/assets/fe8fe616-2595-4776-9ff2-886fcef71b1d)

**Comment by Randulfe** [comment]
Does forking with this fix work for you @darklight9811 ? https://github.com/radix-ui/primitives/pull/3386

**Comment by darklight9811** [comment]
@Randulfe sadly not, the bug Im encountering is here:

![Image](https://github.com/user-attachments/assets/60586d2a-bb7e-41c9-9659-1fc699018a2a)

(maybe the effect without a deps array)

**Comment by DannyDelott** [comment]
We switched from @radix-ui/tootltip to floating-ui (aka Popper.js) and are still seeing this error. I suspect since radix-ui is using floating-ui under the hood this might be an issue with the underlying library and not necessarily an issue with radix-ui itself.

I'm going to see if I can refactor OP's repro sandbox to demonstrate this using floating UI.

**Comment by jarvis394** [comment]
https://github.com/radix-ui/primitives/blob/6e75e117977c9e6ffa939e6951a707f16ba0f95e/packages/react/popper/src/popper.tsx#L73-L89

Is there a reason why `useEffect` here doesn't have a deps array (line 85)? When I add `[context.onAnchorChange]` to the effect dependencies, the error seems to go away.

**Comment by gabrieljim** [comment]
any solution for this? running into the same using popover

**Comment by flbn** [comment]
> It's unlikely to be an issue with the primitive, but rather with the specific setup.
> 
> I will close the issue now, but feel free to keep chatting if you have more info to present.

not to be _that guy_ but @benoitgrelard it's been close to a year and a half with people consistently reproducing this error. `floating-ui` seems to be the underlying cause, but it's a shame this issue was closed and there's been no maintainers coming in here to discuss the issue at all...

anything that uses the popper primitive seems to be susceptible. notably, we've noticed this on context menus. [carbon seems to have been able to get around this with some memoization](https://github.com/carbon-design-system/carbon/pull/17002/files), but @jarvis394 pointed out something that might also be worth looking into. hopefully someone on the radix team sees this.

**Comment by chaance** [comment]
Confirmed the fix from #3614 should do the trick. https://codesandbox.io/p/sandbox/maximum-update-depth-exceeded-crash-forked-v994vf?file=%2Fsrc%2FDemo.tsx%3A31%2C37

**Comment by bakikucukcakiroglu** [comment]
I was having the same issue and updating radix-ui component solved it! Thanks community :)
