### ISSUE TITLE
element.ref deprecation warning in Presence component

### ISSUE THREAD

**Issue by idkgene** [radix-ui/primitives#3200]
### Current Behavior

When interacting with components using Radix UI Presence, the following warning appears:

```
ConsoleError: Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release.
```

### Expected behavior

No console warnings should appear.

### Reproducible example

Repository with minimal reproduction: https://github.com/changeelog/blank-fumadocs-app

Steps to reproduce:

Clone and run the repository
Go to /docs
Click on search bar

### Suggested solution

The warning seems to originate from the Presence component's internal handling of refs. Consider updating the ref handling logic to align with React 19's changes regarding element.ref access.

### Additional context

The warning appears despite package.json indicating support for React 19
While functionality isn't affected, the warning pollutes the console

<details><summary>The full Error Trace is:</summary>
<p>
ConsoleError: Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release.
at handleClientError (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/client/components/react-dev-overlay/internal/helpers/use-error-handler.js:41:17)
at window.console.error (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/client/components/globals/intercept-console-error.js:39:56)
at Object.elementRefGetterWithDeprecationWarning (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/react/cjs/react.development.js:453:17)
at $921a889cee6df7e8$export$99c2b779aa4e8b8b (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/https://github.com/radix-ui+react-presence@[1.0.1_@types](mailto:1.0.1_@types)+react-dom@[18.3.1_@types](mailto:18.3.1_@types)+react@18.3.12_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@radix-ui/react-presence/dist/index.mjs:33:115)
at react-stack-bottom-frame (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:22349:20)
at renderWithHooks (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:5740:22)
at updateFunctionComponent (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:8001:19)
at beginWork (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:9666:18)
at runWithFiberInDEV (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:544:16)
at performUnitOfWork (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:14997:22)
at workLoopSync (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:14827:41)
at renderRootSync (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:14807:11)
at performWorkOnRoot (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:14302:13)
at performSyncWorkOnRoot (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:15867:7)
at flushSyncWorkAcrossRoots_impl (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:15731:21)
at processRootScheduleInMicrotask (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:15765:7)
at eval (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:15883:13)
</p>
</details> 

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    -     | Not sure what uses radix-presence under the hood in this case, the versions should be latest        |
| React            | n/a     | ^18.3.1        |
| Browser          | Arc/Chrome   |  Arc - latest, Chrome - 130.0.6723.71       |
| Assistive tech   | n/a     | n/a     |
| Node             | n/a     | v20.16.0|
| npm/yarn         | pnpm    | 9.7.1   |
| Operating System | Windows | 10 Pro  |

**Comment by changeelog** [comment]
Related issue: fuma-nama/fumadocs#1004

**Comment by prince-juguilon-fgi** [comment]
Hi! may I ask how this issue was fixed? it is marked as completed but I don't see any resolution. Thanks!

**Comment by fokkerone** [comment]
@prince-juguilon-fgi 
 It is not solved. 
 Same issue here
 
Next @latest package.json (^15.0.3) reads 
```
"react": "^18.2.0 || 19.0.0-rc-66855b96-20241106",
"react-dom": "^18.2.0 || 19.0.0-rc-66855b96-20241106",
```
Which means Next @latest uses React 19 if use 18.3.1 like my components and @idkgene does.   
Only solution I found so far is downgrading next to ^14.1.

Otherwise my Library over Radix /shadcn raises this error.

**Comment by idkgene** [comment]
> Hi! may I ask how this issue was fixed? it is marked as completed but I don't see any resolution. Thanks!

Hey, sorry for being late, I gave up on this and decided to completely ignore the issue. When I've _updated_ next (I guess) the issue just disappeared lol

@fokkerone dropped some useful insights on this. Thank you!

If you have a reproduction for this still by any chance I wanna dive deeper in it and leave a PR possibly

**Comment by fokkerone** [comment]
- Does it make sense to force Next 15 to use React 18, as it is optimise to use React 19 features?
- As far as I dig into this there are many libraries facing problems with this breaking change of forwarding Refs (https://github.com/shadcn-ui/ui/issues/3898)
- I guess its the third time React breaking the usage of Refs... urrgz
- React is not aware of this forwardRef problem https://react.dev/blog/2024/04/25/react-19-upgrade-guide#breaking-changes, I didn't find any migration hints onto this topic. 


So I would suggest to export the WithRef for 19 and 18 separately and not use forwardRef in Radix/own Components anymore. 
so don`t do:

```javascript
const SelectTrigger = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Trigger>,
  SelectTriggerProps
>(({ className, color, size, children, ...props }, ref) => {
  const context = React.useContext(SelectContext);
  return (
    <SelectPrimitive.Trigger
      ref={ref}
      className={cn(
        selectTriggerVariants({
          color: context.color || color,
          size: context.size || size,
          className,
        })
      )}
      {...props}
    >
      {children}
      <SelectPrimitive.Icon asChild>
        <Rwe39 className="h-4 w-4 text-primary"></Rwe39>
      </SelectPrimitive.Icon>
    </SelectPrimitive.Trigger>
  );
});```
 
Wrap the forwardRef for 18 and Ref as prop for 19 as an additional export. Thats most ugly but the only solution that pops up in my mind at the moment

... or of if there is any successor over forwardRef, which might be the most convenient/clever way to solve this breaking change, use this.

**Comment by idkgene** [comment]
Instead of maintaining separate exports for React 18 and 19, I suggest a more unified approach for both versions:

```typescript
interface SelectTriggerProps extends React.ComponentProps<typeof SelectPrimitive.Trigger> {
  ref?: React.Ref<HTMLButtonElement>;
}

const SelectTrigger = ({ className, children, ref, ...props }: SelectTriggerProps) => (
  <SelectPrimitive.Trigger
    ref={ref}
    className={cn(
      "flex h-9 w-full items-center justify-between whitespace-nowrap rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring disabled:cursor-not-allowed disabled:opacity-50 [&>span]:line-clamp-1",
      className
    )}
    {...props}
  >
    {children}
    <SelectPrimitive.Icon asChild>
      <ChevronDown className="h-4 w-4 opacity-50" />
    </SelectPrimitive.Icon>
  </SelectPrimitive.Trigger>
)
```

This looks like a good workaround for React library authors until the ecosystem fully adapts to React 19's changes. Looks like no complication and ease of maintenance.

**Comment by idkgene** [comment]
Moreover, we can make this even more elegant using a generic type:
Moreover, we can make this even more elegant using somewhat generic like this:

```typescript
type ComponentWithRef<T extends React.ElementType> = React.ComponentProps<T> & {
  ref?: React.ComponentProps<T>["ref"]
}
```

And just do it like this

```tsx
const SelectTrigger = ({ className, children, ...props }: ComponentWithRef<typeof SelectPrimitive.Trigger>) => (
  <SelectPrimitive.Trigger
    className={cn(
      "flex h-9 w-full items-center justify-between whitespace-nowrap rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring disabled:cursor-not-allowed disabled:opacity-50 [&>span]:line-clamp-1",
      className
    )}
    {...props}
  >
    {children}
    <SelectPrimitive.Icon asChild>
      <ChevronDown className="h-4 w-4 opacity-50" />
    </SelectPrimitive.Icon>
  </SelectPrimitive.Trigger>
)
```

**Comment by fokkerone** [comment]
I must admit now i am lost... ;-) 

Is far is I understood: 
React.ComponentPropsWithRef only sets the type of the props of the component for the ref property to exist (as well as the other native attributes of the underlying element). However, without using React.forwardRef, passing the ref prop has no effect. ref.current will always be whatever initial value was passed to useRef.
https://stackoverflow.com/questions/77018392/react-componentpropswithref-vs-react-forwardref

But reading https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/forward_and_create_ref/#generic-forwardrefs

Makes use of the forwardRef-less/-wrapper  idea you mentioned.
