### ISSUE TITLE
Version inconsistency of @radix-ui/react-context across packages

### ISSUE THREAD

**Issue by davbrito** [radix-ui/primitives#3245]
It seems that the @radix-ui/react-context package does not have the same updated version across all packages. This makes it to be duplicated.

![image](https://github.com/user-attachments/assets/31b11e35-8793-4ce9-939b-9b63172b7b8e)

**Comment by davbrito** [comment]
fixed by d3e300c

**Comment by GavinMeierSonos** [comment]
This isn't fixed for all the packages though, not until all the packages get released with the latest so that they all depend on the same version.
