### ISSUE TITLE
`ScrollArea` doesn't update when the size of children changes

### ISSUE THREAD

**Issue by smhutch** [radix-ui/primitives#639]
### Current Behavior

In my case, I'm looking to compose a Radix `ScrollArea` and `Tabs`. In my case, my JSX is _something like_:

```tsx
// All components are from Radix, or internally render Radix primitives
<Tabs onValueChange={setActiveTab} value={activeTab}>
  <ScrollArea>
    <Tabs.List>
      {loaded ? <ManyTabs /> : null}
    </Tabs.List>
  </ScrollArea>
  <TabPanels />
</Tabs>
```

I created a short [screenshare ](https://www.loom.com/share/e73b2dfc873f4f3f8d095031fda1a161) showing the issue. After some debugging, I found that `--radix-scroll-area-position-height` is set to `1px`, this is a valid height while loading, but results in the content being clipped once the tabs are loaded.

### Expected behavior

When children change, update the size of the `ScrollArea`.

### Reproducible example

This [Sandbox](https://codesandbox.io/s/lucid-sinoussi-wmv86?file=/src/App.tsx) doesn't use `Tabs`, but still replicates the issue

### Suggested solution

Unsure, but happy to help out if this is confirmed as something that should be fixed 🙂

### Additional context

In my case the tabs/children of the ScrollArea are dynamic. By default there are none, but tabs are added by users via another UI. I could hack around this issue by setting a fallback node, but that requires me hard coding a height that is exactly equal to the children. Of course, I would prefer to avoid that 😄 

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  scroll-area       |     0.0.12    |
| React            | n/a     | 17.02        |
| Browser          |  FF       | 88        |
| Assistive tech   | n/a        |         |
| Node             | n/a     |         |
| npm/yarn         |  n/a       |         |
| Operating System |  mac       |      11.3   |

**Comment by jjenzz** [comment]
Hey @smhutch 👋 

Thanks for reporting this. We have a PR up at the moment with a complete overhaul for `ScrollArea` and this was fixed as part of that.

Your issue spurred me to create a storybook story showing this behaviour in action though so thank you for that. You can see it here https://601857eb614bae0021c9b9dd-oxcoozvego.chromatic.com/?path=/story/components-scrollarea--chromatic-dynamic-content-after-loaded

We're hoping to release this next week 🤞

**Comment by smhutch** [comment]
Thanks @jjenzz, that's great! It seems a whole lot more stable now 🎉

**Comment by smhutch** [comment]
@jjenzz I have been reviewing some code at my end, and tried removing the hack I had to work around this. Unfortunately the issue is still occurring on the latest version. Is it the case that your PR has been merged, but not released just yet?

Thanks for your work on this component, your changes in #624 look great 😄

**Comment by benoitgrelard** [comment]
That's correct, the new `ScrollArea` PR was merged but we haven't done a new release yet.

**Comment by benoitgrelard** [comment]
Hey @smhutch, this has now been released.
https://radix-ui.com/primitives/docs/components/scroll-area
